version: '2'

services:
    asterisk:
      build: asterisk
      network_mode: "host"
      privileged: true
      restart: always
      command: asterisk -f
      ports:
        - 5060:5060
      volumes:
        - /data/asterisk/log:/var/log/asterisk
        - ./asterisk/etc:/etc/asterisk
        - /dev:/dev


