version: '2'

services:
    static:
      build: static
      ports:
        - 80:80
    fconf:
      build: fconf
      ports:
        - 8080:8080
      privileged: true
      volumes:
        - /dev:/dev
      network_mode: "host"
    asterisk:
      build: asterisk
      privileged: true
      network_mode: "host"
    telegraf:
      build: telegraf
      ports:
        - 8125/udp:8125/udp
        - 8092/udp:8092/udp
        - 8094:8094
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock


