version: '2'

services:
    drone:
      build: drone
      env_file:
        - ./dronerc.env
      ports:
        - 8000:8000
      volumes:
        - /data/drone:/var/lib/drone
        - /var/run/docker:/var/run/docker
    static:
      build: static
      ports:
        - 80:80
    telegraf:
      build: telegraf
      ports:
        - 8125/udp:8125/udp
        - 8092/udp:8092/udp
        - 8094:8094
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock


